# Generated by Django 4.2.16 on 2024-11-12 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_note_task_project_note_task_taskcompletion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='notes_list',
        ),
    ]
